parameters:
    academic.bug_tracking.issue.class:                      Academic\Bundle\BugTrackingBundle\Entity\Issue
    academic.bug_tracking.form.type.issue.class:            Academic\Bundle\BugTrackingBundle\Form\Type\IssueType
    academic.bug_tracking.form.handler.issue.class:         Academic\Bundle\BugTrackingBundle\Form\Handler\IssueHandler
    academic.bug_tracking.form.listener.issue.class:        Academic\Bundle\BugTrackingBundle\Form\EventListener\IssueSubscriber
    academic.bug_tracking.provider.chart.issue.class:       Academic\Bundle\BugTrackingBundle\Provider\IssueChartDataProvider
    academic.bug_tracking.placeholder.filter.issue.class:   Academic\Bundle\BugTrackingBundle\Placeholder\PlaceholderFilter

services:
    academic.bug_tracking.form.listener.issue:
        class: '%academic.bug_tracking.form.listener.issue.class%'
        arguments:
            - '@form.factory'

    academic.bug_tracking.form.type.issue:
        class: '%academic.bug_tracking.form.type.issue.class%'
        arguments:
            - '%academic.bug_tracking.issue.class%'
            - '@academic.bug_tracking.form.listener.issue'
        tags:
            - { name: form.type, alias: academic_bug_tracking_issue }

    academic.bug_tracking.form.handler.issue:
        class: '%academic.bug_tracking.form.handler.issue.class%'
        scope: request
        arguments:
            - '@request'
            - '@oro_entity.doctrine_helper'
            - '@oro_entity.routing_helper'

    academic.bug_tracking.provider.chart.issue:
        class: '%academic.bug_tracking.provider.chart.issue.class%'
        arguments:
            - '@oro_entity.doctrine_helper'

    academic.bug_tracking.placeholder.filter.issue:
        class: '%academic.bug_tracking.placeholder.filter.issue.class%'
        scope: request
        arguments:
            - '@request'