Academic\Bundle\BugTrackingBundle\Entity\Issue:
    properties:
        code:
            - NotBlank: ~
            - Length:
                max: 255
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        description:
             - NotBlank: ~
        type:
             - NotBlank: ~
        resolution:
             - NotBlank: ~
        priority:
             - NotBlank: ~
