datagrids:
    bug-tracking-issues-grid:
        extended_entity_name: '%academic.bug_tracking.issue.class%'
        source:
            type: orm
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - issueType.name as issueTypeName
                    - issuePriority.name as issuePriorityName
                    - issuePriority.priority as issuePriorityValue
                    - issueResolution.name as issueResolutionName
                    - issueReporter.username as issueReporterUsername
                    - issueAssignee.username as issueAssigneeUsername
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: '%academic.bug_tracking.issue.class%', alias: issue }
                join:
                    left:
                        - { join: issue.type, alias: issueType}
                        - { join: issue.priority, alias: issuePriority}
                        - { join: issue.reporter, alias: issueReporter}
                        - { join: issue.assignee, alias: issueAssignee}
                        - { join: issue.resolution, alias: issueResolution}
        columns:
            code:
                label: academic.bugtracking.issue.code.label
            summary:
                label: academic.bugtracking.issue.summary.label
            issueTypeName:
                label: academic.bugtracking.issue.type.label
            issuePriorityName:
                label: academic.bugtracking.issue.priority.label
            issueResolutionName:
                label: academic.bugtracking.issue.resolution.label
            issueReporterUsername:
                label: academic.bugtracking.issue.reporter.label
            issueAssigneeUsername:
                label: academic.bugtracking.issue.assignee.label
            createdAt:
                label: academic.bugtracking.issue.created_at.label
                frontend_type: datetime
            updatedAt:
                label: academic.bugtracking.issue.updated_at.label
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                issueTypeName:
                    data_name: issueTypeName
                issuePriorityName:
                    data_name: issuePriorityValue
                issueResolutionName:
                    data_name: issueResolutionName
                issueReporterUsername:
                    data_name: issueReporterUsername
                issueAssigneeUsername:
                    data_name: issueAssigneeUsername
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type: string
                    data_name: issue.code
                summary:
                    type: string
                    data_name: issue.summary
                issueTypeName:
                    type:      enum
                    data_name: issueTypeName
                    enum_code: oac_issue_type
                issuePriorityName:
                    type:      enum
                    data_name: issuePriorityName
                    enum_code: oac_issue_priority
                issueResolutionName:
                    type:      enum
                    data_name: issueResolutionName
                    enum_code: oac_issue_resolution
                issueReporterUsername:
                    type: string
                    data_name: issueReporterUsername
                issueAssigneeUsername:
                    type: string
                    data_name: issueAssigneeUsername
                createdAt:
                    type: datetime
                    data_name: createdAt
                updatedAt:
                    type: datetime
                    data_name: updatedAt
        properties:
            id: ~
            update_link:
                type: url
                route: academic_bug_tracking_update
                params:
                    - id
            view_link:
                type: url
                route: academic_bug_tracking_view
                params:
                    - id
        actions:
            edit:
                type: navigate
                label: academic.bugtracking.grid.actions.edit.label
                link: update_link
                icon: edit
            view:
                type: navigate
                label: academic.bugtracking.grid.actions.view.label
                link: view_link
                icon: view
                rowAction:  true

    bug-tracking-issues-recent-grid:
        extends: bug-tracking-issues-grid
        source:
            query:
                where:
                    and:
                        - :user_id MEMBER OF issue.collaborators
            bind_parameters:
                - user_id
        filters: ~
        sorters: ~
        options:
            toolbarOptions:
                hide: true
                pagination:
                    onePage: true
                pageSize:
                    items: [10]
                    default_per_page: 10